### ISSUE TITLE
Please update your sample to include onClick on the item as well.

### ISSUE THREAD

**Issue by mayankwadhwa** [fraggjkee/DataBindingRecyclerAdapter#1]
The solution for the onclick in your second article doesn't make sense to me so can you please update your sample to have an example of onclick listener as well.

**Comment by mayankwadhwa** [comment]
Hey i finally understood your solution. I basically need to create a wrapper around the POJO class and create an onclick function on it. I was able to do it with your solution thank you

**Comment by fraggjkee** [comment]
Hey, yes, you've got the idea right. You can skip the wrapping step if it's okay for you to have onClick-like methods right in your data classes. I'll extend the sample project with more examples a little bit later. Thanks!

**Comment by mayankwadhwa** [comment]
Thanks for taking the time to reply. I was wondering if you have any idea how to call root viewmodel or activity from the new wrapper.

**Comment by fraggjkee** [comment]
It depends on the technologies you use or prefer. It can be done using [Subject](http://reactivex.io/documentation/subject.html) in Rx or [Flow](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-flow/) with Coroutines. The idea in both cases is very similar: you emit events from list item wrappers/entities/view models and observe these emissions from the parent view model:

```
class ItemViewModel {

     private val clicks = PublishSubject.create<Click>()

     fun onButton1Click() = clicks.onNext(Click.Button1)
     fun onButton2Click() = clicks.onNext(Click.Button2)

     fun observeClicks(): Observable<Click> = clicks.hide()

     sealed class Click {
         object Button1 : Click()
         object Button2 : Click()
     }
}
```

and since your root view models "owns" list items and creates them it can do something like this:

```
class MyViewModel : ViewModel() {

       val items = MutableLiveData<List<RecyclerItem>>()

       fun loadData() {
             items.value = someData
                   .onEach { observeItemEvents(it) }
                   .map { it.toRecyclerItem() } 
       }

       private observeItemEvents(viewModel: ItemViewModel) {
               disposables += viewModel.observeClicks()
                      .subscribe { click -> 
                    when (click) {
                            ItemViewModel.Click.Button1 -> { /* handle click */ }
                            ItemViewModel.Click.Button2 -> { /* handle click */ }
                     }
        }
       }
}
```

Alternatively, you can use simple labmda for callbacks if you don't have neither Rx nor Coroutines.

**Comment by mayankwadhwa** [comment]
Thank you for the help man

**Comment by mayankwadhwa** [comment]
Hey man i am just curious that you recommending flow and Subjects but not LiveData, Is there any particular reason for that?

**Comment by fraggjkee** [comment]
Please use whatever makes sense for you and your project, basically it has nothing to do with the library, it's just a common pattern of delivering events from one layer to another. Personally I don't think that LiveData is a good tool for building event streams as it wasn't designed for that (it stores the latest event and that makes no sense for your particular case - stream of events). If you rotate your device LiveData will re-emit the most recent click and again that is not what you probably need.

**Comment by mayankwadhwa** [comment]
Thank you for the explaination man 👍 👍
